### PR TITLE
added sample data and sample output files

### PR DESCRIPTION
**Pull request by zhangl64**
@miranska  please review. Thanks.

### CODE REVIEW

**Comment by miranska** [comment]
@zhangl64 , Travis build is failing -- please take a look

**Comment by zhangl64** [comment]
@miranska , thanks for the heads-up, I added a new commit, now we still have some warnings of package conflicts, but we don't have some errors. 78047fb69fc0f9982ea9286f46a20bce7bd677a3

**Comment by zhangl64** [comment]
It's weird, the error message is:
```
Error: '../restore/data/old.csv' does not exist in current working directory ('/home/travis/build/miranska/restore/RESTORE.Rcheck').
Execution halted
* checking for unstated dependencies in â€˜testsâ€™ ... OK
* checking tests ... OK
  Running â€˜testthat.Râ€™
* checking PDF version of manual ... OK
* DONE
Status: 1 ERROR, 4 WARNINGs, 3 NOTEs
```
However, I tried on my local machine with the `Check Package` function in RStudio, it doesn't throw any errors.

**Comment by zhangl64** [comment]
Is there anyway that I can see the content in `'/home/travis/build/miranska/restore/RESTORE.Rcheck'`?

**Comment by zhangl64** [comment]
```
Error: '../restore/data/old.csv' does not exist in current working directory ('/home/travis/build/miranska/restore/RESTORE.Rcheck').
Execution halted
* checking for unstated dependencies in â€˜testsâ€™ ... OK
* checking tests ... OK
  Running â€˜testthat.Râ€™
* checking PDF version of manual ... OK
* DONE
Status: 1 ERROR, 4 WARNINGs, 3 NOTEs
```
The error above can be resolved by changing the directory in `@examples`. The reason is that the `RESTORE.Rcheck` folder is under the root directory in the server, but it is outside the root directory in my computer, hence a conflict. Thus, I have to change the directory to pass the test here. But the local `check R package` will be fail.

**Pull request merged**
